Transaction Edit UI
jaimejazarenoiii/kwartracker-android pull request #27
Opened 2021-05-17 10:22 UTC by danacealfonso

# 📲 What #

* Transaction edit UI

# ✅ Acceptance criteria #

- [x ] Tested it locally?

# ⏰ TODO #

* Create transaction edit UI

# 🔗 References #

![Screen Shot 2021-05-17 at 5 58 03 PM](https://user-images.githubusercontent.com/44434044/118472466-72afa800-b73b-11eb-8df3-24b23f825ad4.png)

2021-05-20 04:06 UTC, rexendy requested changes
- once the api is implemented. pls remove all static values 
ex. name (Juan), image (received.jpg)

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_add_1.xml
> +                    android:textColor="#414141"
pls add to colors.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_add_1.xml
> +                    android:textColor="#414141"
pls add to colors.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +            android:text="Edit Transaction"
pls add to strings.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +            android:textColor="#7AF1F3F6"
pls add to colors.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                            android:textColor="#BBC3C9"
pls add to colors.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                            android:textColor="#414141"
pls add to colors.xml and strings.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                            android:text="Button"
pls add to strings.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                        android:textColor="#BBC3C9"
pls add to colors.xml and strings.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                        android:textColor="#414141"
pls add to colors.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                            android:textColor="#414141"
pls add to colors.xml and strings.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                            android:text="Button"
pls add to strings.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                            android:textColor="#BBC3C9"
pls add to colors.xml and strings.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                            android:inputType="text"
pls add to colors.xml and strings.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                            android:text="Button"
pls add to strings.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +
remove space

tools:ignore="HardcodedText,ContentDescription" />

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                            android:textColor="#BBC3C9"
pls add to colors.xml and strings.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                            android:textColor="#414141"
pls add to colors.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                            android:text="Button"
pls add to strings.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                        android:textColor="#BBC3C9"
pls add to colors.xml and strings.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                        android:textColor="#414141"
pls add to colors.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                        android:textColor="#BBC3C9"
pls add to colors.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                        android:textColor="#BBC3C9"
pls add to colors.xm

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/layout/fragment_transaction_edit.xml
> +                        android:text="Replace"
pls add to strings.xml

2021-05-20 04:06 UTC, rexendy commented on app/src/main/res/navigation/nav_graph.xml
> +        android:label="Transaction Edit"
pls add to strings.xml

2021-05-20 08:54 UTC, danacealfonso commented
> * once the api is implemented. pls remove all static values
>   ex. name (Juan), image (received.jpg)

will do Ms. @rexendy

2021-05-20 09:00 UTC, rexendy approved these changes

2021-05-20 09:40 UTC, MarvinBlanca approved these changes

2021-05-21 01:05 UTC, jupilot11 approved these changes

2021-05-21 04:01 UTC, kalvinbdr approved these changes

2021-05-21 10:15 UTC, merged