- Implement Add wallet Ui
jaimejazarenoiii/kwartracker-android pull request #29
Opened 2021-05-18 11:18 UTC by jupilot11

# 📲 What #

* Implement UI for add wallet

# 🤔 Why #

* It is a new feature

# ✅ Acceptance criteria #

- [ X] Tested it locally?
- [ ] Passing Unit Tests/UI [Tests?](
https://user-images.githubusercontent.com/23349947/118642237-b246c480-b80d-11eb-8864-56939dff6289.mov
)

# 🔗 References #

* URLs or Images or Ticket links.

2021-05-19 01:51 UTC, kalvinbdr approved these changes

2021-05-19 03:03 UTC, MarvinBlanca approved these changes

2021-05-19 03:03 UTC, MarvinBlanca approved these changes

2021-05-19 03:29 UTC, danacealfonso approved these changes

2021-05-20 04:15 UTC, rexendy requested changes

2021-05-20 04:15 UTC, rexendy commented on app/src/main/java/com/kwartracker/android/wallet/ui/add/AddWalletFragment.kt
> +        listOf(WalletType(id = 1, title = "Wallet"), WalletType(id = 2, title = "Savings"))
pls add Wallet and Savings to strings.xml  since this is static

2021-05-20 04:15 UTC, rexendy commented on app/src/main/res/drawable/switch_track.xml
> +            <solid android:color="#80C51200"/>
pls add color to colors.xml

2021-05-20 04:15 UTC, rexendy commented on app/src/main/res/navigation/nav_graph.xml
> +        android:label="Add Wallet"
pls add to strings.xml

2021-05-21 03:10 UTC, rexendy approved these changes

2021-05-21 03:52 UTC, merged