- Create change password ui
jaimejazarenoiii/kwartracker-android pull request #30
Opened 2021-05-19 03:05 UTC by MarvinBlanca

# 📲 What #

* Pull request to add change password ui

# 🛠 How #

* Create change password ui

# ✅ Acceptance criteria #

* [X] Tested locally

# ⏰ TODO #

* None

# 🔗 References #

<img width="377" alt="Screen Shot 2021-05-19 at 10 52 23 AM" src="https://user-images.githubusercontent.com/43373740/118750126-6178af80-b891-11eb-81d1-f6a39870bbf2.png">

2021-05-20 04:17 UTC, rexendy approved these changes

2021-05-20 23:27 UTC, danacealfonso approved these changes

2021-05-21 01:06 UTC, jupilot11 approved these changes

2021-05-21 03:59 UTC, kalvinbdr requested changes

2021-05-21 03:59 UTC, kalvinbdr commented on app/src/main/java/com/kwartracker/android/settings/changePassword/ui/ChangePasswordFragment.kt
> +package com.kwartracker.android.settings.changePassword.ui
@MarvinBlanca 
Change package path to `app/src/main/java/com/kwartracker/android/settings/ui/changepassword/ChangePasswordFragment.kt`

2021-05-21 09:15 UTC, kalvinbdr approved these changes

2021-05-21 09:31 UTC, merged