Feature/add navigation
jaimejazarenoiii/kwartracker-android pull request #35
Opened 2021-05-27 03:43 UTC by MarvinBlanca

# 📲 What #

* Pull request to add navigation to fragments

# 🛠 How #

* Create button listeners on fragments  

# ✅ Acceptance criteria #

* [X] Tested locally

# ⏰ TODO #

* None

# 🔗 References #

2021-05-27 04:03 UTC, danacealfonso approved these changes

2021-05-28 10:07 UTC, rexendy requested changes

2021-05-28 10:07 UTC, rexendy commented on app/src/main/java/com/kwartracker/android/settings/ui/SettingsFragment.kt
> +                Toast.makeText(activity, "No Categories UI", Toast.LENGTH_SHORT).show()
pls add the text to strings.xml

2021-05-28 10:07 UTC, rexendy commented on app/src/main/java/com/kwartracker/android/settings/ui/categories/CategoryDetailFragment.kt
> +                Toast.makeText(activity, "Edit Category Clicked", Toast.LENGTH_SHORT).show()
pls add the text to strings.xml

2021-05-28 10:07 UTC, rexendy commented on app/src/main/java/com/kwartracker/android/settings/ui/changepassword/ChangePasswordFragment.kt
> +                Toast.makeText(activity, "Saving changes...", Toast.LENGTH_SHORT).show()
pls add the text to strings.xml

2021-05-28 10:07 UTC, rexendy commented on app/src/main/res/navigation/nav_graph.xml
> +        android:label="ChangePasswordFragment" />
pls add labels to strings.xml

2021-05-31 04:07 UTC, rexendy requested changes

2021-05-31 04:07 UTC, rexendy commented on app/src/main/java/com/kwartracker/android/profile/ui/edit/EditProfileFragment.kt
> +            }
Pls add the text to strings.xml

2021-05-31 04:07 UTC, rexendy commented on app/src/main/java/com/kwartracker/android/settings/ui/SettingsFragment.kt
> +                Toast.makeText(activity, "No Categories UI", Toast.LENGTH_SHORT).show()
same here, pls add to strings.xml

2021-05-31 04:07 UTC, rexendy commented on app/src/main/java/com/kwartracker/android/settings/ui/categories/CategoryDetailFragment.kt
> +                Toast.makeText(activity, "Edit Category Clicked", Toast.LENGTH_SHORT).show()
same here pls add to strings.xml

2021-05-31 04:07 UTC, rexendy commented on app/src/main/java/com/kwartracker/android/settings/ui/changepassword/ChangePasswordFragment.kt
> +                Toast.makeText(activity, "Saving changes...", Toast.LENGTH_SHORT).show()
same here pls add to strings.xml

2021-06-03 04:07 UTC, jupilot11 approved these changes

2021-06-03 05:28 UTC, kalvinbdr approved these changes

2021-06-07 07:22 UTC, rexendy approved these changes

2021-06-08 02:18 UTC, merged